package com.sf;

import cn.hutool.core.util.StrUtil;
import com.sf.entity.SfLicensePlateConfigParam;

import java.util.HashSet;
import java.util.Set;

public class LicensePlates {
    public static void main(String[] args) {
        SfLicensePlateConfigParam param = new SfLicensePlateConfigParam();

        // 用换行符分割字符串
        String[] platesArray = input.split("\n");

        // 创建一个 List 来存储车牌
        Set<String> licensePlates = new HashSet<>();

        // 遍历处理后的数组，并将其存入 List 中
        for (String plate : platesArray) {
            // 去除字符串两端的空白字符
            String processedPlate = plate.trim();
            // 如果字符串不为空，则加入到列表中
            if (!processedPlate.isEmpty()) {
                licensePlates.add(processedPlate.trim());
            }
        }
        param.setIsDeleted(0);
        param.setLicensePlates(licensePlates);

        System.out.println("\""+StrUtil.join("\",\"",licensePlates)+ "\"");
        // 打印存储的车牌
   //     System.out.println(JSON.toJSONString(param));
//        for (String plate : licensePlates) {
//            System.out.println(plate);
//        }
    }


    // 输入的车牌字符串
    public static final  String input = "赣CLW80挂\n" +
            "鲁DTQ59挂\n" +
            "赣CMQ13挂\n" +
            "鲁DFQ05挂\n" +
            "鲁DDA71挂\n" +
            "鲁DFL89挂\n" +
            "鲁DV998挂\n" +
            "鲁DDH63挂\n" +
            "赣CMZ80挂\n" +
            "鲁DRR01挂\n" +
            "赣CBD27挂\n" +
            "赣CKR32挂\n" +
            "鲁DFQ82挂\n" +
            "鲁DDK09挂\n" +
            "皖G8720挂\n" +
            "皖G8730挂\n" +
            "赣CNL11挂\n" +
            "鲁DSV55挂\n" +
            "鲁DV733挂\n" +
            "赣CBA90挂\n" +
            "冀AEN75挂\n" +
            "赣CBV31挂\n" +
            "赣CBQ12挂\n" +
            "冀A75SR挂\n" +
            "粤ANE77挂\n" +
            "冀A91AT挂\n" +
            "粤ANS11挂\n" +
            "粤ALB69挂\n" +
            "粤ANP06挂\n" +
            "冀A91CR挂\n" +
            "赣CLF70挂\n" +
            "赣CLX01挂\n" +
            "皖CGA03挂\n" +
            "皖CHA02挂\n" +
            "皖CHT33挂\n" +
            "浙ACR36挂\n" +
            "冀E10FA挂\n" +
            "冀EYM04挂\n" +
            "冀E26GA挂\n" +
            "冀E92FG挂\n" +
            "吉AX718挂\n" +
            "吉AY552挂\n" +
            "吉AY721挂\n" +
            "吉AX785挂\n" +
            "吉AY372挂\n" +
            "吉AY567挂\n" +
            "吉AY916挂\n" +
            "吉AX372挂\n" +
            "吉AW548挂\n" +
            "吉AU086挂\n" +
            "吉A900A挂\n" +
            "吉AZ125挂\n" +
            "吉AZ681挂\n" +
            "吉A859B挂\n" +
            "吉A832A挂\n" +
            "吉AZ581挂\n" +
            "吉A111B挂\n" +
            "吉AW087挂\n" +
            "吉AW766挂\n" +
            "吉AR153挂\n" +
            "吉AQ128挂\n" +
            "吉AX657挂\n" +
            "吉AX952挂\n" +
            "吉AS890挂\n" +
            "吉AX228挂\n" +
            "吉AU768挂\n" +
            "吉AW333挂\n" +
            "辽H9X44挂\n" +
            "辽H7Q50挂\n" +
            "辽H3X92挂\n" +
            "辽H3Y02挂\n" +
            "辽H3V62挂\n" +
            "辽H2R60挂\n" +
            "辽H8P33挂\n" +
            "辽H7R51挂\n" +
            "辽H9R37挂\n" +
            "辽H3W01挂\n" +
            "辽H2Q50挂\n" +
            "吉AX968挂\n" +
            "吉AY422挂\n" +
            "吉AY222挂\n" +
            "吉A003A挂\n" +
            "吉A000B挂\n" +
            "吉AZ776挂\n" +
            "吉A886B挂\n" +
            "吉AZ279挂\n" +
            "吉AZ833挂\n" +
            "吉A159D挂\n" +
            "吉A790D挂\n" +
            "吉A868D挂\n" +
            "吉A582C挂\n" +
            "吉A515D挂\n" +
            "吉A611D挂\n" +
            "吉A380F挂\n" +
            "吉A892E挂\n" +
            "赣CFG90挂\n" +
            "吉A856N挂\n" +
            "吉AQ587挂\n" +
            "吉A295R挂\n" +
            "吉A673J挂\n" +
            "吉A186K挂\n" +
            "吉A680N挂\n" +
            "吉A550L挂\n" +
            "吉A992P挂\n" +
            "吉A754F挂\n" +
            "吉A673K挂\n" +
            "吉AF121挂\n" +
            "吉A060P挂\n" +
            "吉A954Q挂\n" +
            "吉A232P挂\n" +
            "赣CHR00挂\n" +
            "赣CKD87挂\n" +
            "吉A484A挂\n" +
            "吉A183S挂\n" +
            "吉A505R挂\n" +
            "吉A069N挂\n" +
            "吉A705U挂\n" +
            "吉A535U挂\n" +
            "吉A665D挂\n" +
            "吉A070T挂\n" +
            "吉AX066挂\n" +
            "赣CLJ76挂\n" +
            "赣CKQ59挂\n" +
            "赣CLK49挂\n" +
            "赣CLR72挂\n" +
            "赣CKN71挂\n" +
            "赣CFL41挂\n" +
            "赣CKF38挂\n" +
            "赣CHH46挂\n" +
            "赣CKC46挂\n" +
            "赣CBS37挂\n" +
            "赣CBS05挂\n" +
            "赣CBN51挂\n" +
            "赣CKT60挂\n" +
            "赣CKS42挂\n" +
            "赣CKQ47挂\n" +
            "赣CKW45挂\n" +
            "赣CLY15挂\n" +
            "赣CKQ40挂\n" +
            "赣CHD41挂\n" +
            "吉A385N挂\n" +
            "吉A682M挂\n" +
            "吉A586P挂\n" +
            "吉A993R挂\n" +
            "吉A227M挂\n" +
            "吉A758U挂\n" +
            "吉AX655挂\n" +
            "吉A922F挂\n" +
            "吉A509S挂\n" +
            "吉A672L挂\n" +
            "吉A090N挂\n" +
            "吉A913C挂\n" +
            "吉A494U挂\n" +
            "吉AJ721挂\n" +
            "吉A317F挂\n" +
            "吉A873F挂\n" +
            "吉A197L挂\n" +
            "吉A019R挂\n" +
            "吉A353L挂\n" +
            "吉AX073挂\n" +
            "吉A610Q挂\n" +
            "吉A988M挂\n" +
            "粤S9566挂\n" +
            "粤BCB23挂\n" +
            "冀AQ514挂\n" +
            "冀ARN67挂\n" +
            "冀A141T挂\n" +
            "冀A72XL挂\n" +
            "辽AT269挂\n" +
            "辽AW978挂\n" +
            "辽AV708挂\n" +
            "辽AU335挂\n" +
            "辽AQ482挂\n" +
            "辽AV102挂\n" +
            "辽AV870挂\n" +
            "辽AT930挂\n" +
            "辽AU997挂\n" +
            "辽AU157挂\n" +
            "辽AT761挂\n" +
            "沪DL709挂\n" +
            "沪BG773挂\n" +
            "沪L2898挂\n" +
            "赣CBK11挂\n" +
            "赣CBP20挂\n" +
            "冀A23MP挂\n" +
            "赣CBN79挂\n" +
            "冀APZ07挂\n" +
            "冀A69XQ挂\n" +
            "冀ABP89挂\n" +
            "冀A98Q9挂\n" +
            "冀A690N挂\n" +
            "冀A3D69挂\n" +
            "冀A044M挂\n" +
            "赣CBS19挂\n" +
            "鲁G5Z83挂\n" +
            "赣CLW08挂\n" +
            "赣CLX77挂\n" +
            "桂H0183挂\n" +
            "粤BP889挂\n" +
            "沪K1036挂\n" +
            "沪BE317挂\n" +
            "沪AX212挂\n" +
            "沪AM553挂\n" +
            "冀A65EU挂\n" +
            "辽AT658挂\n" +
            "赣CKK22挂\n" +
            "赣CKA51挂\n" +
            "赣CKA27挂\n" +
            "赣CKW27挂\n" +
            "赣CKE41挂\n" +
            "赣CHU43挂\n" +
            "赣CHF49挂\n" +
            "赣CKX80挂\n" +
            "赣CKB60挂\n" +
            "赣CHH40挂\n" +
            "赣CKU27挂\n" +
            "赣CKZ12挂\n" +
            "赣CKS25挂\n" +
            "赣CKK10挂\n" +
            "赣CKY43挂\n" +
            "赣CHE49挂\n" +
            "赣CKC41挂\n" +
            "赣CEV16挂\n" +
            "赣CEB40挂\n" +
            "赣CKP46挂\n" +
            "赣CCS46挂\n" +
            "赣CEV27挂\n" +
            "赣CHS49挂\n" +
            "赣CCN30挂\n" +
            "赣CCS27挂\n" +
            "赣CHS46挂\n" +
            "赣CKM40挂\n" +
            "赣CEA82挂\n" +
            "赣CKG80挂\n" +
            "赣CEV65挂\n" +
            "赣CKD45挂\n" +
            "赣CKE20挂\n" +
            "赣CKS43挂\n" +
            "赣CKU48挂\n" +
            "赣CKR48挂\n" +
            "赣CKK00挂\n" +
            "赣CKL48挂\n" +
            "赣CKA53挂\n" +
            "赣CKZ80挂\n" +
            "赣CFX10挂\n" +
            "赣CHQ42挂\n" +
            "赣CKU49挂\n" +
            "赣CEP97挂\n" +
            "赣DM102挂\n" +
            "赣DT553挂\n" +
            "赣DU050挂\n" +
            "赣DT300挂\n" +
            "赣DS931挂\n" +
            "赣DY791挂\n" +
            "赣DS471挂\n" +
            "赣DN047挂\n" +
            "赣DY180挂\n" +
            "赣DS412挂\n" +
            "赣DY195挂\n" +
            "赣DY510挂\n" +
            "赣DS413挂\n" +
            "赣DN401挂\n" +
            "赣DS745挂\n" +
            "赣DN142挂\n" +
            "赣DN241挂\n" +
            "赣DZ276挂\n" +
            "赣DZ121挂\n" +
            "赣DZ013挂\n" +
            "赣D7A72挂\n" +
            "辽G2D58挂\n" +
            "辽G2C26挂\n" +
            "辽G6C38挂\n" +
            "黑AA660挂\n" +
            "赣CAY67挂\n" +
            "黑AA137挂\n" +
            "黑AB053挂\n" +
            "黑AB202挂\n" +
            "黑AB258挂\n" +
            "黑AB515挂\n" +
            "黑AA150挂\n" +
            "黑AA045挂\n" +
            "黑AA210挂\n" +
            "黑AB388挂\n" +
            "黑AA334挂\n" +
            "黑AA217挂\n" +
            "黑AB238挂\n" +
            "黑AB279挂\n" +
            "黑AB322挂\n" +
            "黑AA702挂\n" +
            "赣CBR61挂\n" +
            "黑AA139挂\n" +
            "黑AA133挂\n" +
            "黑AA785挂\n" +
            "黑AA269挂\n" +
            "黑AB309挂\n" +
            "黑AA831挂\n" +
            "黑AA126挂\n" +
            "黑AA226挂\n" +
            "黑AA691挂\n" +
            "黑AB365挂\n" +
            "黑AB239挂\n" +
            "黑AB217挂\n" +
            "黑A9973挂\n" +
            "黑AA227挂\n" +
            "黑AA216挂\n" +
            "黑AA725挂\n" +
            "黑AB218挂\n" +
            "黑AA136挂\n" +
            "赣CBU26挂\n" +
            "赣CDM03挂\n" +
            "黑AA239挂\n" +
            "黑AB338挂\n" +
            "黑AB281挂\n" +
            "黑AA131挂\n" +
            "黑AA212挂\n" +
            "赣CBR92挂\n" +
            "赣CDC72挂\n" +
            "黑AA128挂\n" +
            "黑AA230挂\n" +
            "黑AB305挂\n" +
            "黑AA129挂\n" +
            "赣CDY17挂\n" +
            "黑AA229挂\n" +
            "赣F13E7挂\n" +
            "黑AA232挂\n" +
            "粤BS805挂\n" +
            "赣CBB60挂\n" +
            "赣CDJ12挂\n" +
            "赣FE227挂\n" +
            "黑AA195挂\n" +
            "黑AA193挂\n" +
            "赣CBR16挂\n" +
            "赣CAZ70挂\n" +
            "赣F91E1挂\n" +
            "赣CBT61挂\n" +
            "沪BW713挂\n" +
            "黑AB273挂\n" +
            "赣CCJ71挂\n" +
            "赣CBR22挂\n" +
            "赣CAT93挂\n" +
            "黑AA156挂\n" +
            "赣CCC60挂\n" +
            "赣CBR05挂\n" +
            "黑AA823挂\n" +
            "赣CBR35挂\n" +
            "赣CAP52挂\n" +
            "黑AA143挂\n" +
            "黑AA130挂\n" +
            "黑AA218挂\n" +
            "黑AA929挂\n" +
            "黑AB299挂\n" +
            "黑AB197挂\n" +
            "黑AB517挂\n" +
            "赣CCD72挂\n" +
            "赣CCH02挂\n" +
            "赣CBT70挂\n" +
            "赣CBT38挂\n" +
            "赣CBT50挂\n" +
            "赣CBT35挂\n" +
            "赣CBT52挂\n" +
            "赣CAU30挂\n" +
            "赣CAZ10挂\n" +
            "赣CBQ93挂\n" +
            "赣CBN01挂\n" +
            "赣CBP95挂\n" +
            "赣CBZ63挂\n" +
            "赣CBW03挂\n" +
            "赣CBV80挂\n" +
            "赣CBR63挂\n" +
            "赣CBR93挂\n" +
            "赣CBT31挂\n" +
            "赣CAB69挂\n" +
            "赣CAZ50挂\n" +
            "赣CAU60挂\n" +
            "赣CAU85挂\n" +
            "赣CAN71挂\n" +
            "赣CAP78挂\n" +
            "赣CAN53挂\n" +
            "赣CAR28挂\n" +
            "赣CAX76挂\n" +
            "赣CAR87挂\n" +
            "赣CAK96挂\n" +
            "赣CBR11挂\n" +
            "赣CDK10挂\n" +
            "赣CDU51挂\n" +
            "赣CDB43挂\n" +
            "赣CDC43挂\n" +
            "赣CDM41挂\n" +
            "赣CDC09挂\n" +
            "赣CDF45挂\n" +
            "赣CDF01挂\n" +
            "赣CDZ91挂\n" +
            "赣CDY81挂\n" +
            "赣CDC49挂\n" +
            "赣CDG43挂\n" +
            "赣CDE91挂\n" +
            "赣CCW39挂\n" +
            "赣CCW76挂\n" +
            "赣CCW26挂\n" +
            "赣CCW32挂\n" +
            "赣CAY37挂\n" +
            "黑AA252挂\n" +
            "黑AA762挂\n" +
            "黑AB328挂\n" +
            "赣F5E33挂\n" +
            "赣F666C挂\n" +
            "赣F7E11挂\n" +
            "粤BE438挂\n" +
            "沪L0531挂\n" +
            "粤BSC07挂\n" +
            "赣CDA13挂\n" +
            "赣CAS01挂\n" +
            "赣CAN90挂\n" +
            "赣CAX57挂\n" +
            "赣CBZ35挂\n" +
            "赣CAZ56挂\n" +
            "赣CBE40挂\n" +
            "赣CAG00挂\n" +
            "赣CEU57挂\n" +
            "赣CET48挂\n" +
            "赣CER25挂\n" +
            "赣CEJ35挂\n" +
            "赣CEB48挂\n" +
            "赣CDE71挂\n" +
            "赣CDE62挂\n" +
            "赣CDL79挂\n" +
            "赣CDB26挂\n" +
            "赣CDF55挂\n" +
            "赣CDE19挂\n" +
            "赣CDC51挂\n" +
            "赣CDC08挂\n" +
            "赣CDB32挂\n" +
            "赣CDA31挂\n" +
            "赣CAN60挂\n" +
            "赣CBC41挂\n" +
            "赣CAX50挂\n" +
            "赣CER62挂\n" +
            "沪DH201挂\n" +
            "沪DU735挂\n" +
            "沪DB157挂\n" +
            "沪DS110挂\n" +
            "沪DJ772挂\n" +
            "沪DU716挂\n" +
            "沪DH325挂\n" +
            "沪DS201挂\n" +
            "沪K7765挂\n" +
            "沪K5638挂\n" +
            "沪K6012挂\n" +
            "沪J6132挂\n" +
            "沪K3731挂\n" +
            "沪K0832挂\n" +
            "沪J7713挂\n" +
            "沪J7933挂\n" +
            "赣CBZ89挂\n" +
            "赣CAR52挂\n" +
            "赣CBT42挂\n" +
            "赣CAG42挂\n" +
            "赣CAP47挂\n" +
            "赣CDF97挂\n" +
            "赣CDE50挂\n" +
            "赣CDC59挂\n" +
            "赣CDA76挂\n" +
            "赣CAP63挂\n" +
            "赣CBZ91挂\n" +
            "赣CBZ70挂\n" +
            "赣CAD26挂\n" +
            "赣CDA42挂\n" +
            "赣CAP58挂\n" +
            "赣CBT41挂\n" +
            "赣CBE41挂\n" +
            "赣CBZ41挂\n" +
            "赣CBC27挂\n" +
            "赣CDB49挂\n" +
            "赣CBZ59挂\n" +
            "赣CAV17挂\n" +
            "赣CAN41挂\n" +
            "赣C44H5挂\n" +
            "赣CER32挂\n" +
            "赣CEZ17挂\n" +
            "赣CEY10挂\n" +
            "赣CEN52挂\n" +
            "赣CEN60挂\n" +
            "赣CEM91挂\n" +
            "赣CEJ90挂\n" +
            "赣CEJ10挂\n" +
            "赣CEB80挂\n" +
            "赣CCE47挂\n" +
            "赣CDD89挂\n" +
            "赣CBU60挂\n" +
            "赣CAW42挂\n" +
            "赣CAH60挂\n" +
            "新A6C73挂\n" +
            "新MJ010挂\n" +
            "新MH891挂\n" +
            "新MJ108挂\n";
}